/**
 * Demo catalogue used by "Seed dummy products". Titles are generated by
 * combining templates, brands and variants so thousands of distinct items can
 * be created; every seeded product has isDummy=true and can be wiped from the
 * admin screen in one tap.
 */
export interface SeedCategory {
  slug: string;
  name: string;
  children: { slug: string; name: string; items: string[]; brands: string[]; price: [number, number] }[];
}

export const SEED_CATALOG: SeedCategory[] = [
  {
    slug: 'electronics', name: 'Electronics',
    children: [
      { slug: 'mobiles', name: 'Mobile Phones', items: ['5G Smartphone 128GB', 'Smartphone 256GB', 'Foldable Phone', 'Rugged Phone', 'Feature Phone Dual SIM'], brands: ['Novo', 'Zentra', 'Pixelon', 'Orbit', 'Kairo'], price: [2999, 89999] },
      { slug: 'laptops', name: 'Laptops & Computers', items: ['Thin & Light Laptop 16GB', 'Gaming Laptop RTX', '2-in-1 Touch Laptop', 'Chromebook 14"', 'Mini PC i5'], brands: ['Vertex', 'Lumio', 'Acrona', 'Delton'], price: [18999, 159999] },
      { slug: 'audio', name: 'Headphones & Audio', items: ['Wireless Earbuds ANC', 'Over-Ear Headphones', 'Bluetooth Speaker', 'Soundbar 2.1', 'Neckband Earphones'], brands: ['Bassik', 'Sonora', 'Echo Lab', 'Tunex'], price: [499, 24999] },
      { slug: 'cameras', name: 'Cameras & Photo', items: ['Mirrorless Camera Kit', 'Action Camera 4K', 'Instant Camera', 'Camera Tripod', 'Ring Light 18"'], brands: ['Optika', 'Fotix', 'Lensa'], price: [999, 99999] },
      { slug: 'wearables', name: 'Smart Watches', items: ['Smart Watch AMOLED', 'Fitness Band', 'Kids GPS Watch', 'Smart Ring'], brands: ['Fitro', 'Pulse', 'Timeo'], price: [1299, 29999] },
    ],
  },
  {
    slug: 'fashion', name: 'Fashion',
    children: [
      { slug: 'mens-clothing', name: "Men's Clothing", items: ['Cotton Polo T-Shirt', 'Slim Fit Jeans', 'Formal Shirt', 'Hooded Sweatshirt', 'Kurta Set'], brands: ['Urbano', 'Royal Thread', 'Denimco', 'Kaya'], price: [399, 3999] },
      { slug: 'womens-clothing', name: "Women's Clothing", items: ['Printed Kurti', 'Maxi Dress', 'Silk Saree', 'Denim Jacket', 'Palazzo Set'], brands: ['Aanya', 'Silkroute', 'Mira', 'Vastra'], price: [499, 7999] },
      { slug: 'shoes', name: 'Shoes', items: ['Running Shoes', 'Leather Sneakers', 'Casual Loafers', 'Sports Sandals', 'Formal Oxford Shoes'], brands: ['Stride', 'Kickz', 'Footly', 'Treko'], price: [599, 8999] },
      { slug: 'bags', name: 'Bags & Luggage', items: ['Laptop Backpack', 'Trolley Bag 24"', 'Leather Wallet', 'Handbag', 'Duffel Bag'], brands: ['Carryon', 'Bagwise', 'Nomad'], price: [299, 9999] },
    ],
  },
  {
    slug: 'home-garden', name: 'Home & Garden',
    children: [
      { slug: 'kitchen', name: 'Kitchen & Dining', items: ['Non-Stick Cookware Set', 'Mixer Grinder 750W', 'Air Fryer 4L', 'Pressure Cooker 5L', 'Dinner Set 24 Pcs'], brands: ['Cookwell', 'Homora', 'Prestiva'], price: [499, 12999] },
      { slug: 'furniture', name: 'Furniture', items: ['Ergonomic Office Chair', 'Study Table', 'Bookshelf 5 Tier', 'Bean Bag XXL', 'Shoe Rack'], brands: ['Woodnest', 'Comfy', 'Urbanwood'], price: [999, 24999] },
      { slug: 'decor', name: 'Home Decor', items: ['Wall Clock', 'LED String Lights', 'Ceramic Vase', 'Cotton Bedsheet Double', 'Blackout Curtains'], brands: ['Decora', 'Nest & Co', 'Artisan'], price: [199, 4999] },
      { slug: 'garden', name: 'Garden & Outdoor', items: ['Garden Tool Kit', 'Self-Watering Planter', 'Outdoor Solar Lights', 'Hose Pipe 15m'], brands: ['Greenly', 'Bloom'], price: [249, 3999] },
    ],
  },
  {
    slug: 'sports', name: 'Sporting Goods',
    children: [
      { slug: 'fitness', name: 'Fitness Equipment', items: ['Adjustable Dumbbells', 'Yoga Mat 6mm', 'Resistance Bands Set', 'Treadmill Foldable', 'Skipping Rope'], brands: ['Fitzone', 'Powerflex', 'Active'], price: [199, 39999] },
      { slug: 'cricket', name: 'Cricket', items: ['English Willow Bat', 'Cricket Ball Leather', 'Batting Gloves', 'Cricket Kit Bag'], brands: ['Willowcraft', 'Sixer', 'Boundary'], price: [299, 14999] },
      { slug: 'cycling', name: 'Cycling', items: ['Mountain Bike 21 Speed', 'Cycling Helmet', 'Bike Light Set'], brands: ['Velo', 'Trailx'], price: [499, 29999] },
    ],
  },
  {
    slug: 'toys', name: 'Toys & Hobbies',
    children: [
      { slug: 'kids-toys', name: 'Kids Toys', items: ['Building Blocks 500 Pcs', 'Remote Control Car', 'Soft Teddy Bear', 'Board Game Family', 'Puzzle 1000 Pcs'], brands: ['Playo', 'Funbox', 'Kidzy'], price: [199, 4999] },
      { slug: 'collectibles', name: 'Collectibles & Art', items: ['Vintage Coin Set', 'Die-cast Model Car', 'Canvas Painting', 'Action Figure'], brands: ['Heritage', 'Collecto'], price: [299, 19999] },
    ],
  },
  {
    slug: 'health-beauty', name: 'Health & Beauty',
    children: [
      { slug: 'skincare', name: 'Skin Care', items: ['Vitamin C Serum', 'Sunscreen SPF 50', 'Face Wash 150ml', 'Moisturiser 100g'], brands: ['Glowa', 'Purely', 'Derma+'], price: [149, 1999] },
      { slug: 'grooming', name: 'Grooming', items: ['Beard Trimmer', 'Hair Dryer 1200W', 'Electric Toothbrush', 'Perfume 100ml'], brands: ['Groomx', 'Styla', 'Aroma'], price: [399, 5999] },
    ],
  },
  {
    slug: 'motors', name: 'Motors',
    children: [
      { slug: 'auto-accessories', name: 'Car & Bike Accessories', items: ['Car Phone Holder', 'Bike Helmet ISI', 'Car Vacuum Cleaner', 'Dash Cam 1080p', 'Tyre Inflator'], brands: ['Autopro', 'Ridex', 'Motomate'], price: [199, 7999] },
    ],
  },
  {
    slug: 'books', name: 'Books & Stationery',
    children: [
      { slug: 'books', name: 'Books', items: ['Bestselling Novel', 'Self-Help Paperback', 'Competitive Exam Guide', "Children's Story Book"], brands: ['Pageturn', 'Inkwell'], price: [99, 1499] },
      { slug: 'stationery', name: 'Stationery', items: ['Fountain Pen Set', 'Spiral Notebook Pack', 'Art Colour Set'], brands: ['Scribe', 'Penco'], price: [49, 1999] },
    ],
  },
  {
    slug: 'jewellery', name: 'Jewellery & Watches',
    children: [
      { slug: 'jewellery-items', name: 'Jewellery', items: ['Gold Plated Necklace Set', 'Silver Ring 925', 'Oxidised Jhumka', 'Bangles Set'], brands: ['Swarna', 'Rajwada', 'Silvra'], price: [199, 14999] },
      { slug: 'watches', name: 'Watches', items: ['Analog Watch Leather', 'Chronograph Steel Watch', 'Digital Sports Watch'], brands: ['Timeo', 'Horologe'], price: [499, 19999] },
    ],
  },
];

export const VARIANTS = ['Black', 'Blue', 'Red', 'White', 'Grey', 'Green', 'Gold', 'Silver', 'Navy', 'Maroon', 'Pink', 'Beige'];
export const EDITIONS = ['', '2026 Edition', 'Pro', 'Lite', 'Max', 'Combo Pack', 'Premium', 'Value Pack'];
export const CONDITION_WEIGHTS: [string, number][] = [['NEW', 0.78], ['OPEN_BOX', 0.08], ['REFURBISHED', 0.09], ['USED', 0.05]];

/** Image URL for a demo product. Picsum is free, needs no key and is stable per seed. */
export const demoImage = (seed: string, n: number) => `https://picsum.photos/seed/${encodeURIComponent(`${seed}-${n}`)}/800/800`;
